import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  body: {
    width: '100%',
    height: '100%',
    padding: 20,
  },
  txtLungangen: {
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: 24,
    color: '#FF5E00',
    marginLeft: 20,
  },
  contaiTxt: {
    justifyContent: 'center',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    width: '100%',
    height: 48,
    padding: 10,
    borderWidth: 0.2,
    borderRadius: 6,
    borderColor: '#4E4B66',
    backgroundColor: '#fff',
    marginTop: 20,
  },
  imgserch: {
    position: 'absolute',
    top: '50%',
    left: '5%',
  },
  scrolView: {
    marginTop: 20,
    width: '100%',
    height: '100%',
  },
  contaiicon: {
    marginLeft: 10,
    flexDirection: 'column',
    width: 100,
    alignItems: 'center',
  },
  imgicon: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#EDD0FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon2: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FFD9BA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contaiscrol:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginBottom:20,
  },
  imgicon3: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FACCCC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon4: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FBC1BD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon5: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FFE299',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon6: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#D3E5C4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon7: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FFC0C0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon8: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FFDEF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon9: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#FECA97',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgicon10: {
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: '#D6FAE9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
})